name: Norg to markdown conversion

on:
  push:
    branches:
      - trunk

jobs:
  convert-norg-to-md:
    name: Generate markdown from norg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          version: v0.9.0
          neovim: true

      - name: Run converter
        run: tools/convert_norg_to_markdown

      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ ! -z $(git status -s) ]]; then
            find . -name "*.md" -not -path "./subprojects/*" -not -path "./.tests/*" | xargs git add
            git commit -m "chore(docs): generate markdown from norg files"
          fi

      - name: Push to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: "B4mbus/haumea"
          branch: trunk
